### ISSUE TITLE
General to-do list

### ISSUE THREAD

**Issue by KrzysztofDusko** [KrzysztofDusko/Just-Data#189]
- [x] first preview with Avalonia (https://avaloniaui.net/)
- [ ] add new readme
- [ ] release Avalonia Windows/MacOS/Linux version
- [ ] release "Just Data Evo Windows" WPF based ? 
- [ ] release MIT licensed Avalonia version
- [ ] release AOT verson (probably limited) ([https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/](url))
